### ISSUE TITLE
Check whether non-validating XML in gitdox XML documents is really invalid

### ISSUE THREAD

**Issue by amir-zeldes** [cligu/gitdox#36]
If it's invalid -> please fix.
If not, comment in this issue with a pasted example of the thing that's triggering non-validity, but should be valid (I will adjust the schema to allow it)

**Comment by ctschroeder** [comment]
all non-validating XML in gitdox appears legit invalid. No false negatives.  (I didn't fix all the invalid XML, because other people are working on them.)
