### ISSUE TITLE
Scriptorium skin metadata popup window no longer customized

### ISSUE THREAD

**Issue by ctschroeder** [cligu/gitdox#43]
The scriptorium skin/flavor of Gitdox is showing example metadata field and data in the metadata pop-up that are different from what we had originally.  It looks like something perhaps from an English language project.  (Note:  I'm talking about the examples not the drop drown menu -- see "superman" in this image)
<img width="357" alt="screen shot 2017-07-18 at 7 49 56 pm" src="https://user-images.githubusercontent.com/4079217/28348532-5c5b7d88-6bf2-11e7-97c5-710e0569d67f.png">
Any way to go back to what we had before?  (I think corpus was our example?) or maybe we could use author if you want something that works across projects?  Thanks!

**Comment by amir-zeldes** [comment]
Yes, I see the problem - it leaked in from the parallel installation. Author is a good idea!
