### ISSUE TITLE
Disappearing corpus metadata

### ISSUE THREAD

**Issue by eplatte** [cligu/gitdox#59]
Corpus metadata disappears, seemingly after corpus metadata is added to a different corpus. In other words, GitDox seems to support only one set of corpus-level metadata at a time. In the Coptic SCRIPTORIUM instance, corpus metadata has been added to AP, Johannes Canons, and Pseudo-Theophilus, the latter most recently. Only the Pseudo-Theophilus corpus metadata currently displays/exists.

**Comment by amir-zeldes** [comment]
Caused by literal 'NULL' string in doc_id/corpus_meta in modules/gitdox_sql.py
